<?php

require_once 'palestra_quiz.functions.inc';

/*
 * Implements hook_menu()
 */
function palestra_quiz_menu() {
  $items['quiz'] = array(
    'page callback'   => 'drupal_get_form',
    'page arguments'  => array('_palestra_quiz_form'),
    'access callback' => TRUE,
    'file'            => 'palestra_quiz.functions.inc'
  );

  $items['quiz/vote'] = array(
    'page callback'   => '_palestra_quiz_vote_computed',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK
  );

  $items['quiz/placar'] = array(
    'page callback'   => '_palestra_quiz_result',
    'access callback' => TRUE,
    'type'            => MENU_NORMAL_ITEM
  );

  $items['quiz/result'] = array(
    'page callback'   => '_palestra_quiz_result_callback',
    'access callback' => TRUE,
    'type'            => MENU_CALLBACK
  );

  return $items;
}

/*
 * Implementation of hook_theme().
 */
function palestra_quiz_theme(){
  return array(
    'quiz' => array(
      'template' => 'templates/quiz',
    ),
  );
}
